### PR TITLE
[SELS-TASK] Improved Category List Page

### PR DESCRIPTION
**Pull request by christanplaza**
Description: **Front-End** Update on Display Categories Function
[Commands]
php artisan db:seed (This is to add 1 category to the DB)

[Pre-condition]
The DB must be seeded.
Proceed to localhost:8000/categories

[Expected Output] 
There should be three categories on display in a card-group as opposed to the old Unordered List

[Notes]
The titles aren't clickable yet as the specific detail page for each category is not implemented yet

### CODE REVIEW

**Comment by jeremiahC** [comment]
@christanplaza 
I want to confirm if this PR is for applying user interface on category page?

**Comment by christanplaza** [comment]
> @christanplaza
> I want to confirm if this PR is for applying user interface on category page?

Yes, this is only to improve the page for Listing Categories. The categories was displayed only as a List, in this update, the categories will now be displayed as cards, in preparation for pagination.

**Comment by jeremiahC** [comment]
@christanplaza 
Can you include here the button, since this is user interface, please apply the button according to the specs given

[Image from Gyazo](https://gyazo.com/6ef41887a3b653c5b252a22fe0faf53f)

**Comment by christanplaza** [comment]
> Can you include here the button, since this is user interface, please apply the button according to the specs given

Noted, will update it in a bit.

**Comment by christanplaza** [comment]
> @christanplaza
> Can you include here the button, since this is user interface, please apply the button according to the specs given

This has been resolved in df5581792c45e56102180e7a13b70b78fdf6c30b

**Review by jeremiahC — APPROVED** [review]
-UI follows the specs that is given
- Code is clean

**Pull request merged**
