### PR TITLE
[SELS-TASK] Implemented Delete Category Function

### PR DESCRIPTION
**Pull request by christanplaza**
Description: Front-end and Back-end implementation for Delete Category Function
[Commands]
php artisan db:seed (This is to add 1 category to the DB)

[Pre-condition]
Requires that the DB is seeded with at least 1 category
Proceed to localhost:8000/1/edit
Click on the Delete button

[Expected Output]
It should automatically redirect you to /categories the category list should be empty.

[Notes]
Error displays for invalid input is not implemented yet but will be in the future.

### CODE REVIEW

**Comment by jeremiahC** [comment]
@christanplaza 
The delete button should be on the list page not on the edit page, as described in the wireframe
[Image from Gyazo](https://gyazo.com/cad174b45d3bfa7bca17cce61a213ae6)

please check requirements and follow it because, in actual project this is what client wants

**Comment by christanplaza** [comment]
@jeremiahC This is resolved in my latest branch for Admin Panel
Screenshot from 2019-06-20 17-08-20

**Comment by jeremiahC** [comment]
> @jeremiahC This is resolved in my latest branch for Admin Panel
> Screenshot from 2019-06-20 17-08-20

so the delete button is temporary only?

**Comment by christanplaza** [comment]
Yes, this was also for the purpose of having the controllers set-up and ready for Route Restrictions. It will be refactored and modified as view for when the Lessons and Words are implemented.

**Review by jeremiahC — APPROVED** [review]

**Pull request merged**
